### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'func'

### ISSUE THREAD

**Issue by charlieh0tel** [0x9900/SA818#4]
```
pi@pirim:~/src/SA818.ch $ ./sa818.py 
Traceback (most recent call last):
  File "./sa818.py", line 342, in <module>
    main()
  File "./sa818.py", line 332, in main
    if opts.func == 'version':
AttributeError: 'Namespace' object has no attribute 'func'
pi@pirim:~/src/SA818.ch $ 

```
I don't see this on x86_64 ubuntu.  So .... ??

Pi: Package: python3 Version: 3.7.3-1
Ubuntu: python3 Version: 3.8.2-0ubuntu2

**Comment by 0x9900** [comment]
One of the subcommands should be mandatory.

```
% ./sa818.py
sa818: error: the following arguments are required: {radio,volume,filters,version}
```
